### ISSUE TITLE
unclear input file requirement for new models: `vae_model_dir`

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#104]
Hello! I am interested in using SOPHIE to build a new model. Following the instructions in `new_model_experiment/1_process_and_train_vae`, there is one input file that I can't figure out:

```
Directory (vae_model_dir) containing trained VAE model (.h5 files) from the previous notebook.
```
https://github.com/greenelab/generic-expression-patterns/blob/master/new_model_experiment/1_process_and_train_vae.py#L44

What is the previous notebook? I don't think there is a previous notebook in this directory, so I'm not sure what this refers to. Any help would be greatly appreciated!

**Comment by ajlee21** [comment]
This step is not clearly written. Thank you for point this out. So this directory refers to something like [this](https://github.com/greenelab/generic-expression-patterns/tree/master/pseudomonas_analysis/models/NN_2500_30) where the VAE model (i.e learned weights) are stored. The "previous_notebook" part is referring to the fact that the [first notebook](https://github.com/greenelab/generic-expression-patterns/blob/master/new_model_experiment/1_process_and_train_vae.ipynb) trains the model that the [second notebook](https://github.com/greenelab/generic-expression-patterns/blob/master/new_model_experiment/2_identify_common_and_specific_genes.ipynb) uses.

I hope this helps to clarify things. I'll update these directions. Especially to account for if a user wants to use an existing vs train a new model

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/3
