### ISSUE TITLE
Config file/documentation discrepancy for `processed_compendium_filename`

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#108]
The instructions in [1_process_and_train_vae.ipynb](https://github.com/greenelab/generic-expression-patterns/blob/master/new_model_experiment/1_process_and_train_vae.ipynb) say that the training compendium used to train VAE should be listed in the config file as `processed_compendium_filename`, however the example config file for a new model ([config_new_model_experiment.tsv](https://github.com/greenelab/generic-expression-patterns/blob/fa56a2df12c1b17e4dd0a03fd3693d51e8f31bbd/configs/config_new_model_experiment.tsv)) does not have this field. What should it be input as?

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/2
