### ISSUE TITLE
Advice for determining a good size for latent dimensions for a new model experiment

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#109]
Do you have any heuristic/general advice for determining a good size for the latent dimensions variable for a new model experiment? I don't have any intuition about what reasonable values may be, or how higher/lower values may impact the outcome of the model building process.

**Comment by taylorreiter** [comment]
(notes from meeting with Alex) 
This is fairly subjective. This is based on adage, which had 300, so that was the starting point.

Two layers:
    + Intermediate layer: just picked half of the input dimensions.
    + Latent dimension: supposed for be 300? Think of the latent space a potentially capturing pathways. There are probably a range of architectures that will work.

To evaluate the architecture, use the loss curve. Make sure they go down and converge (stay level). Also plotted the way the data was distributed in the latent space. If you simulated a bunch of experiments and have the original data set, make sure those overlap.

Also evaluated by pulling out experiments to make sure related groups of genes were found together, and that these correspond to a perturbation.

**Comment by ajlee21** [comment]
This issue is referenced as a resource in https://github.com/greenelab/sophie/pull/3
