### ISSUE TITLE
required granularity for `experiment_to_sample_filename` when building a new model

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#111]
What is the required/preferred level of granularity for specifying the experiments in `experiment_to_sample_filename` when building a new model? Can I use something like BioProject, which delineates samples that were collected for the same experiment, or do I need to label all wild type cells and try and curate similar treatments? 

More details: I'm hoping to build a new Pseudomonas aeruginosa (Pa) model. I plan to use the raw strain PA14 compedium built by @georgiadoing (file here https://osf.io/uvpsa/), but limit it to samples that were labelled as PA14 (annotated here https://raw.githubusercontent.com/greenelab/core-accessory-interactome/master/data/metadata/SRA_annotations.tsv). My plan is to label experiments by their BioProject ID (e.g. all RNAseq sample collected for a specific experiment), since many aren't labelled super well for condition (e.g. wildtype/control, treatment, etc). Is this sufficient, or will this mess up the model training process?

**Comment by taylorreiter** [comment]
(notes from a conversation with alex)
only need metadata for the held out target set of samples. Don't actually need metadata for any of the samples you're using for training. SOPHIE uses everything, and generates a set of background experiments that essentially end up acting like the controls that your samples get compared against. 

the `experiment_to_sample_filename` for the template experiment, and it states which binary comparison to perform for differential expression.

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/3
