### ISSUE TITLE
error with `utils.read_config`: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#112]
While trying to run the notebook [1_process_and_train_vae.ipynb](https://github.com/greenelab/generic-expression-patterns/blob/master/new_model_experiment/1_process_and_train_vae.ipynb), I run into the following error when trying to read my config file:

```
params = utils.read_config(config_filename)
```

```
Traceback (most recent call last):

  File "/Users/tr/miniconda3/envs/sophie/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-11-d766e35dacd0>", line 1, in <module>
    params = utils.read_config(config_filename)

  File "/Users/tr/miniconda3/envs/sophie/lib/python3.7/site-packages/ponyo/utils.py", line 17, in read_config
    config_dict[items[0]] = eval(items[1])

  File "<string>", line 1
    /Users/tr/github/generic_expression_patterns/
    ^
SyntaxError: invalid syntax
```

I'm working on a mac, and I installed the environment with the `environment.yml` file provided in this repo.

Any help as to what could be causing this error, and how to fix it, would be greatly appreciated!

**Comment by ajlee21** [comment]
My guess is that its something in your config file - that its expecting a different format or something. Do you want to share your config file?

Here is the code for reading the config file if that helps: https://github.com/greenelab/ponyo/blob/master/ponyo/utils.py

**Comment by taylorreiter** [comment]
Thanks for sharing the ponyo code, I'll take a look and see if I find anything. I've also attached the config file i was using (I added the .txt extension to be compatible with github uploading rules)

[config_new_model_experiment_pao1.tsv.txt](https://github.com/greenelab/generic-expression-patterns/files/8399130/config_new_model_experiment_pao1.tsv.txt)

**Comment by taylorreiter** [comment]
So the error is coming from `config_dict[items[0]] = eval(items[1])`, specifically the `eval()` function

**Comment by ajlee21** [comment]
I think this is happening because its expecting values to be strings or integers. So you just need to add quotations around your paths like [here](https://raw.githubusercontent.com/greenelab/generic-expression-patterns/fa56a2df12c1b17e4dd0a03fd3693d51e8f31bbd/configs/config_new_model_experiment.tsv)

**Comment by taylorreiter** [comment]
Yup that fixed it, thank you! Note -- the tsv config file shouldn't be edited in excel (at least on a mac), as it may eat the quotes or add more quotes upon writing the file to disk.

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/2
