### ISSUE TITLE
the notebook `1_process_and_train_vae.ipynb` unecessarily contains code to create a raw template experiment

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#115]
In the section `Get raw template experiment`, the notebook `1_process_and_train_vae.ipynb` unecessarily contains code to create a raw template experiment. 

This section was sort of confusing for me, probably because my template experiment does not come from my compendium. I think it could be helpful to either subset this section out to a different notebook, or explicitly add notes that it's not necessary to run it to train the VAE. 

It was also a little confusing because the code requires a `project_id` to be included in the metadata file, but that isn't a format necessary in other template metadata files such as the `*groups.tsv` files (e.g like [here](https://github.com/greenelab/generic-expression-patterns/blob/4e0855d94b3bc426868e1ebcc84516ca861f0dff/pseudomonas_analysis/data/metadata/E-GEOD-17179_groups.tsv))

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/3
