### ISSUE TITLE
DESeq2 warning about metadata variables that are integers

### ISSUE THREAD

**Issue by taylorreiter** [greenelab/generic-expression-patterns#118]
When running the DESeq2 analysis, we get the following warning:

```
R[write to console]:   the design formula contains one or more numeric variables with integer values,
  specifying a model with increasing fold change for higher values.
  did you mean for this to be a factor? if so, first convert
  this variable to a factor using the factor() function
```

This stems from the formatting of the group metadata file:
```
sample  group
M631    2
M632    2
M633    2
SRX8487076      1
SRX8487077      1
SRX8487078      1
```

Where the groups are designated by integers. Although I'm not 100% sure what sophie is doing under the hood, I'm pretty sure this variable should be converted to a factor before running deseq2. Thoughts?

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/sophie/pull/3
