### ISSUE TITLE
Relative paths when sourcing R modules

### ISSUE THREAD

**Issue by dongbohu** [greenelab/generic-expression-patterns#24]
The following two notebooks:
  - `human_analysis/1_process_recount2_data.ipynb
  - `human_analysis/2_identify_generic_genes_pathways.ipynb`

include a few occurrences of lines like this:
```
%%R ...

source("../generic_expression_patterns_modules/filename.R')
...
```
Relying on the relative path in notebook is tricky, because any (accidental) change on the working directory would stop these `source` lines from working. I suggest that we change all R calls that include `source` into:
```
%%R -i base_dir ...

source(paste(base_dir, 'generic_expression_patterns_modules/filename.R', sep='/'))
...
```

**Comment by ajlee21** [comment]
This [PR](https://github.com/greenelab/generic-expression-patterns/pull/40) makes this update in the test notebooks as a test case. This change seems to work. Next we will update the other analysis notebooks in a future PR.

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/generic-expression-patterns/pull/42
