### ISSUE TITLE
Output in "human_analysis" notebooks 

### ISSUE THREAD

**Issue by dongbohu** [greenelab/generic-expression-patterns#25]
The following two notebooks:

- `human_analysis/1_process_recount2_data.ipynb`
- `human_analysis/2_identify_generic_genes_pathways.ipynb`

don't have outputs right now. To make them more user-friendly, we may want to have some of the outputs included.

**Comment by ajlee21** [comment]
Notebook were rerun to populate cell outputs in this PR: https://github.com/greenelab/generic-expression-patterns/pull/36
