### ISSUE TITLE
Rename "generic_expression_patterns_modules"?

### ISSUE THREAD

**Issue by dongbohu** [greenelab/generic-expression-patterns#27]
Since the repo is named `generic-expression-patterns`, the subdirectory name `generic_expression_patterns_modules` seems a little too long and redundant. Does it make sense to rename it to something like `analysis_modules`? (My first thought was simply `modules`, but that seems too generic.)

**Comment by ajlee21** [comment]
This is definitely a very good idea. Since this project is wrapping up I will leave the directory name as is but keep this in mind as a guide for my future projects
