### ISSUE TITLE
"np.random.seed()" in human_anlysis/2_identify_generic_genes_pathways.ipynb

### ISSUE THREAD

**Issue by dongbohu** [greenelab/generic-expression-patterns#28]
Is this line needed in `2_identify_generic_genes_pathways.ipynb`?
```
np.random.seed(123)
```

**Comment by dongbohu** [comment]
When this line is removed from `tests/2_identify_generic_genes_pathways.ipynb` (see PR #31), the test still passes. So it's probably not needed in `huaman_analysis/2_identify_generic_genes_pathways.ipynb` either.

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/generic-expression-patterns/pull/42
