### ISSUE TITLE
Remove "get_wd()" and "set_wd()" when downloading recount2 data

### ISSUE THREAD

**Issue by dongbohu** [greenelab/generic-expression-patterns#29]
The following two functions in R:
https://github.com/greenelab/generic-expression-patterns/blob/47f763cc23723156173decc4dd3640ca25a683ca/generic_expression_patterns_modules/download_recount2_data.R#L12
and
https://github.com/greenelab/generic-expression-patterns/blob/47f763cc23723156173decc4dd3640ca25a683ca/generic_expression_patterns_modules/download_recount2_data.R#L140

use `get_wd()` and `set_wd(...)` because they call `download_study(...)` with default arguments, so the downloaded files will be saved in `./<project_id>/` directory.

According to https://rdrr.io/bioc/recount/man/download_study.html, we can use `outdir` argument to specify the location of downloaded files. So the function call will be like this:
```
project_dir <- paste(download_dir, project_id, sep='/')
download_study(project_id, outdir=project_dir)
...
```

This will not only make the code cleaner, but also avoid the possible danger of changing the working directory (see #24).

**Comment by ajlee21** [comment]
This [PR](https://github.com/greenelab/generic-expression-patterns/pull/40) makes this update in the test notebooks as a test case. This change seems to work. Next we will update the other analysis notebooks in a future PR.

**Comment by ajlee21** [comment]
Addressed in https://github.com/greenelab/generic-expression-patterns/pull/40
