### ISSUE TITLE
Higher precision in compendium file?

### ISSUE THREAD

**Issue by dongbohu** [greenelab/generic-expression-patterns#32]
Right now the normalized compendium file is saved with three digits after digital point:
https://github.com/greenelab/generic-expression-patterns/blob/fee9c0b1ea51efa607701da7c0ebc93fa31a1e60/generic_expression_patterns_modules/process.py#L729-L730

For higher precision in this file, the `float_format='%.3f'` argument can be deleted. But that means other output files (such as outputs from VAE training, and those generated by `human_analysis/2_identify_generic_genes_pathways.ipynb`) should be regenerated to keep the downstream results consistent.

**Comment by ajlee21** [comment]
I understand the reason to change this, but since this project is wrapping up I will leave it as is for now. I don't anticipate this change to change the results
