### ISSUE TITLE
Comments provided by Tessa (first SOPHIE user)

### ISSUE THREAD

**Issue by ajlee21** [greenelab/generic-expression-patterns#84]
Below are comments provided by Tessa:

- Sklearn version. 0.23.2

- I commented out gxx_linux-64 from yml file because it was stopping my install. I’m pretty sure that’s something you would only need to install in order to use it to install other stuff with pip, and I didn’t run into any other issues starting up from the yml, so I left it as-is, but it could be that’s contributing to some of my issues. 

- Made it through step 8! For step 9, i got an error FileNotFoundError:

 [Errno 2] No such file or directory: '/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/pseudo_experiment/template_normalized_data_aspirin-all_test.txt'

I created a pseudo_experiment directory and ran it again, which got me further. 

- Additional issues — the notebook doesn’t say that the groups .tsv needs to be in the folder /data/metadata, I had them in the /data folder but it’s all good. 

- I installed the package and then have been using a different folder for my analysis. I had to copy over the generic_expression_pattern_modules folder to get through the R bit. Have hit on a new issue: 

 cannot open file '/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophieDE_stats/DE_stats_template_data_aspirin-all_real.txt': No such file or directory

Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection

I suspect this is something going wonky with R not automatically adding slashes into its equivalent of os.path.join in the back end (I’m more comfortable with R than python, and I was very confused last week when I discovered that os.path.join did this!). Mostly thinking that because there’s no slash between Sophie and DE_stats. I went in and modified the DE_analysis.R file to add those slashes in, and now it works. 

- In the second of the R boxes I had to modify line 9 to read "        "/pseudo_experiment/selected_simulated_data_",
because it was trying to save in a directory sophiepseudo_experiment (which doesn’t exist).

**Comment by tessadgreen** [comment]
For the slashes--I will need to test it, but I think the issue was that I didn't have a "/' at the end of my "local_dir" in the config file. Python didn't care but R needs it. I fixed the issue by going in and modifying your code, but fixing the config is definitely easier/better
