### ISSUE TITLE
How to modify config file for multiple analyses of the same dataset

### ISSUE THREAD

**Issue by tessadgreen** [greenelab/generic-expression-patterns#88]
When creating a new config file for analysis of subsets of the samples, which of the file names do I need to change?

I have two example config files below, where one is using the full set of samples, and the other is looking to just compare two of the groups in isolation...not exactly the most readable, but I essentially only changed the project ID--is that the correct approach, or should I be making experiment-specific files elsewhere? 

`local_dir	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie"
raw_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/bulkRNA_countmat.txt"
mapped_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/aspirin_mapped.txt"
normalized_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/aspirin_normalized.txt"
processed_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/aspirin_processed.txt"
mapped_compendium_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/metadata/mapped_recount2_compendium.tsv"
normalized_compendium_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/metadata/normalized_recount2_compendium.tsv"
scaler_filename	"/Users/tgreen/Documents/GitHub/sophie/human_general_analysis/data/scaler_transform_human.pickle"
vae_model_dir	"/Users/tgreen/Documents/GitHub/sophie/human_general_analysis/models/NN_2500_30"
project_id	"aspirin-all"
num_simulated	25
count_threshold	None
latent_dim	30
rank_genes_by	"log2FoldChange"
DE_logFC_name	"log2FoldChange"
DE_pvalue_name	"padj"`

`local_dir	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie"
raw_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/bulkRNA_countmat.txt"
mapped_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/aspirin_mapped.txt"
normalized_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/aspirin_normalized.txt"
processed_template_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/aspirin_processed.txt"
mapped_compendium_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/metadata/mapped_recount2_compendium.tsv"
normalized_compendium_filename	"/Users/tgreen/Dropbox (HMS)/Tessa_DSM/AERD/Projects/Broad-aspirin/sophie/data/metadata/normalized_recount2_compendium.tsv"
scaler_filename	"/Users/tgreen/Documents/GitHub/sophie/human_general_analysis/data/scaler_transform_human.pickle"
vae_model_dir	"/Users/tgreen/Documents/GitHub/sophie/human_general_analysis/models/NN_2500_30"
project_id	"aspirin-all"
num_simulated	25
count_threshold	None
latent_dim	30
rank_genes_by	"log2FoldChange"
DE_logFC_name	"log2FoldChange"
DE_pvalue_name	"padj"`

**Comment by tessadgreen** [comment]
Okay and a followup question: when running the 'Process template and simulate experiments' block I get the following set of messages. 
<img width="603" alt="Screen Shot 2021-07-12 at 4 19 14 PM" src="https://user-images.githubusercontent.com/26631928/125362895-e7165a00-e32c-11eb-94a1-4f9bb481a448.png">

This doesn't seem to explicitly be an error, but when I try to move past it I get a DESeq error:
`Error in DESeqDataSet(se, design = design, ignoreRank) : 
  NA values are not allowed in the count matrix`

As ever, would welcome any troubleshooting suggestions

**Comment by ajlee21** [comment]
Just to clarify what you're asking:

You have a template experiment with 6 total samples (3 in condition 1 vs 3 in condition 2). So you have a my-experiment_groups.tsv file that looks like:

```
Sample	group
Sample_A    1
Sample_B	    1
Sample_C	    1
Sample_D    2
Sample_E    2
Sample_F	    2
```

Then for your next experiment you want to only include 4 of the 6 samples. So you want to have a _groups.tsv file that looks like:
```
Sample	group
Sample_A    1
Sample_B	    1
Sample_D    2
Sample_E    2
```
In order to only include a subset of samples you'll need to specify _process_samples.tsv file in the data/metadata/ directory to specify which samples to keep:
```
Sample	group
Sample_A    1
Sample_B	    1
Sample_C	    drop
Sample_D    2
Sample_E    2
Sample_F	    drop
```

If this is the case you will just need to update the metadata files and then the `project_id` in the config file. Please let me know if I understood your analysis correctly. 

I think this should address your followup issue too. For the followup issue, the print statements are not errors but more to tell you that your samples in your expression data file were not sorted in the same order as the _groups.tsv file so its going to sort the samples to match before performing DE analysis.

**Comment by ajlee21** [comment]
@tessadgreen were you able to get SOPHIE running? If not, I'm wondering if you had a similar issue as described here: https://github.com/greenelab/generic-expression-patterns/issues/117

**Comment by tessadgreen** [comment]
Got sidetracked by another project (per usual) but I think I wasn't able to get the multiple analyses working (though was able to do one-offs without issue). Thanks for the link though, if I get back to it I'll be sure to check that out.
